export const routesConfig = [
  // Public routes
  {
    id: "login",
    path: "/login",
    public: true,
  },
  {
    id: "register",
    path: "/register",
    public: true,
  },
  {
    id: "forgot-password",
    path: "/forgot-password",
    public: true,
  },
  {
    id: "formularios-public-view",
    path: "/formularios/public/:publicSharedId",
    public: true,
  },

  // Protected routes (single source of truth)
  {
    id: "home",
    path: "/",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "tablero",
    path: "/tablero",
    label: "Tablero",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    topNav: true,
    section: "main",
    order: 1,
  },
  {
    id: "dashboard-seguridad",
    path: "/dashboard-seguridad",
    label: "Dashboard SST",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    topNav: true,
    section: "main",
    order: 2,
  },
  {
    id: "panel",
    path: "/panel",
    label: "Panel",
    roles: ["admin", "superdev"],
    showInMenu: true,
    topNav: true,
    section: "main",
    order: 3,
  },
  {
    id: "auditoria",
    path: "/auditoria",
    label: "Auditorias",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 10,
  },
  {
    id: "auditorias-manuales",
    path: "/auditorias-manuales",
    label: "Auditorias Manuales",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 11,
  },
  {
    id: "reporte",
    path: "/reporte",
    label: "Reportes",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 12,
  },
  {
    id: "establecimiento",
    path: "/establecimiento",
    label: "Establecimientos",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "empresas",
    order: 20,
  },
  {
    id: "empleados",
    path: "/empleados",
    label: "Empleados",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "empresas",
    order: 21,
  },
  {
    id: "capacitaciones",
    path: "/capacitaciones",
    label: "Capacitaciones",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 30,
  },
  {
    id: "accidentes",
    path: "/accidentes",
    label: "Accidentes",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 31,
  },
  {
    id: "salud-ocupacional",
    path: "/salud-ocupacional",
    label: "Salud Ocupacional",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 32,
  },
  {
    id: "training",
    path: "/training",
    label: "Training",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 33,
  },
  {
    id: "formulario",
    path: "/formulario",
    label: "Formularios",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "formularios",
    order: 40,
  },
  {
    id: "formularios-publicos",
    path: "/formularios-publicos",
    label: "Formularios Publicos",
    roles: ["admin", "superdev"],
    showInMenu: false,
    section: "formularios",
    order: 41,
  },
  {
    id: "configuracion",
    path: "/configuracion",
    label: "Configuracion",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "sistema",
    order: 50,
  },
  {
    id: "perfil",
    path: "/perfil",
    label: "Perfil",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "sistema",
    order: 51,
  },
  {
    id: "usuarios-logs",
    path: "/usuarios/logs",
    label: "Logs",
    roles: ["superdev"],
    showInMenu: true,
    section: "superdev-tools",
    order: 60,
  },
  {
    id: "debug",
    path: "/debug",
    label: "Debug",
    roles: ["superdev"],
    showInMenu: true,
    section: "superdev-tools",
    order: 61,
  },
  {
    id: "test-controlfile",
    path: "/test-controlfile",
    label: "Test ControlFile",
    roles: ["superdev"],
    showInMenu: true,
    section: "superdev-tools",
    order: 62,
  },

  // Dynamic/internal routes
  {
    id: "auditoria-manual-detalle",
    path: "/auditorias-manuales/:auditoriaId",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "capacitacion-asistencia",
    path: "/capacitacion/:capacitacionId/asistencia",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },

  // Legacy aliases
  {
    id: "legacy-dashboard",
    path: "/dashboard",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    redirectTo: "/tablero",
  },
  {
    id: "legacy-cliente-dashboard",
    path: "/cliente-dashboard",
    roles: ["admin", "superdev"],
    showInMenu: false,
    redirectTo: "/panel",
  },
  {
    id: "legacy-editar",
    path: "/editar",
    roles: ["admin", "superdev"],
    showInMenu: false,
    redirectTo: "/formulario",
  },
  {
    id: "legacy-operario-dashboard",
    path: "/operario-dashboard",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    redirectTo: "/tablero",
  },
];

export const protectedRoutesConfig = routesConfig.filter((route) => !route.public);
export const publicRoutesConfig = routesConfig.filter((route) => route.public);
