export const routesConfig = [
  // Public routes
  {
    id: "login",
    path: "/login",
    public: true,
  },
  {
    id: "register",
    path: "/register",
    public: true,
  },
  {
    id: "forgot-password",
    path: "/forgot-password",
    public: true,
  },
  {
    id: "formularios-public-view",
    path: "/formularios/public/:publicSharedId",
    public: true,
  },
  {
    id: "demo",
    path: "/demo",
    public: true,
  },
  {
    id: "terminos",
    path: "/terminos",
    public: true,
  },
  {
    id: "privacidad",
    path: "/privacidad",
    public: true,
  },

  // Protected routes (single source of truth)
  {
    id: "home",
    path: "/",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "tablero",
    path: "/tablero",
    label: "Tablero",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    topNav: true,
    section: "main",
    order: 1,
    icon: "Home",
  },
  {
    id: "panel",
    path: "/panel",
    label: "Calendario",
    roles: ["admin", "superdev"],
    showInMenu: true,
    topNav: true,
    section: "main",
    order: 3,
    icon: "CalendarToday",
  },
  {
    id: "auditoria",
    path: "/auditoria",
    label: "Auditorias",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 10,
    icon: "Checklist",
  },
  {
    id: "auditorias-manuales",
    path: "/auditorias-manuales",
    label: "Auditorias Manuales",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 11,
    icon: "Assignment",
  },
  {
    id: "reporte",
    path: "/reporte",
    label: "Reportes",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 12,
    icon: "PictureAsPdf",
  },
  {
    id: "congreso-live",
    path: "/congreso-live",
    roles: ["admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "establecimiento",
    path: "/establecimiento",
    label: "Establecimientos",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "empresas",
    order: 20,
    icon: "Business",
  },
  {
    id: "empleados",
    path: "/empleados",
    label: "Empleados",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "empresas",
    order: 21,
    icon: "People",
  },
  {
    id: "capacitacion-vieja",
    path: "/capacitacion-vieja",
    label: "Capacitación vieja",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    section: "higiene",
    order: 30,
    icon: "School",
  },
  {
    id: "accidentes",
    path: "/accidentes",
    label: "Accidentes",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 31,
    icon: "ReportProblem",
  },
  {
    id: "salud-ocupacional",
    path: "/salud-ocupacional",
    label: "Salud Ocupacional",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 32,
    icon: "Healing",
  },
  {
    id: "training",
    path: "/training",
    label: "Capacitaciones",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 33,
    icon: "School",
  },
  {
    id: "dashboard-seguridad",
    path: "/dashboard-seguridad",
    label: "Dashboard",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "higiene",
    order: 30,
    icon: "Dashboard",
  },
  {
    id: "formulario",
    path: "/formulario",
    label: "Formularios",
    roles: ["admin", "superdev"],
    showInMenu: true,
    section: "auditorias",
    order: 40,
    icon: "FormatListBulletedOutlined",
  },
  {
    id: "formularios-publicos",
    path: "/formularios-publicos",
    label: "Formularios Publicos",
    roles: ["admin", "superdev"],
    showInMenu: false,
    section: "formularios",
    order: 41,
    icon: "FormatListBulletedOutlined",
  },
  {
    id: "configuracion",
    path: "/configuracion",
    label: "Configuracion",
    roles: ["admin", "superdev"],
    showInMenu: false,
    section: "sistema",
    order: 50,
    icon: "Settings",
  },
  {
    id: "perfil",
    path: "/perfil",
    label: "Perfil",
    roles: ["operario", "admin", "superdev"],
    showInMenu: true,
    section: "sistema",
    order: 51,
    icon: "Person",
  },
  {
    id: "usuarios-logs",
    path: "/usuarios/logs",
    label: "Logs",
    roles: ["superdev"],
    showInMenu: true,
    section: "superdev-tools",
    order: 60,
    icon: "BadgeOutlined",
  },
  {
    id: "debug",
    path: "/debug",
    label: "Debug",
    roles: ["superdev"],
    showInMenu: true,
    section: "superdev-tools",
    order: 61,
    icon: "BugReport",
  },
  {
    id: "test-controlfile",
    path: "/test-controlfile",
    label: "Test ControlFile",
    roles: ["superdev"],
    showInMenu: true,
    section: "superdev-tools",
    order: 62,
    icon: "Science",
  },

  // Dynamic/internal routes
  {
    id: "training-config",
    path: "/training/config",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "training-plan-items",
    path: "/training/plans/:planId",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "auditoria-manual-detalle",
    path: "/auditorias-manuales/:auditoriaId",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },
  {
    id: "capacitacion-asistencia",
    path: "/capacitacion/:capacitacionId/asistencia",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
  },

  // Legacy aliases
  {
    id: "legacy-ausencias",
    path: "/ausencias",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    redirectTo: "/salud-ocupacional",
  },
  {
    id: "legacy-dashboard",
    path: "/dashboard",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    redirectTo: "/",
  },
  {
    id: "legacy-cliente-dashboard",
    path: "/cliente-dashboard",
    roles: ["admin", "superdev"],
    showInMenu: false,
    redirectTo: "/panel",
  },
  {
    id: "legacy-editar",
    path: "/editar",
    roles: ["admin", "superdev"],
    showInMenu: false,
    redirectTo: "/editar",
  },
  {
    id: "legacy-operario-dashboard",
    path: "/operario-dashboard",
    roles: ["operario", "admin", "superdev"],
    showInMenu: false,
    redirectTo: "/",
  },
];

export const protectedRoutesConfig = routesConfig.filter((route) => !route.public);
export const publicRoutesConfig = routesConfig.filter((route) => route.public);

