// Optimización de importaciones de Material-UI
// Importar solo los componentes necesarios para reducir el tamaño del bundle

// Componentes básicos de Material-UI
export { default as Box } from '@mui/material/Box';
export { default as Button } from '@mui/material/Button';
export { default as TextField } from '@mui/material/TextField';
export { default as Typography } from '@mui/material/Typography';
export { default as Paper } from '@mui/material/Paper';
export { default as Container } from '@mui/material/Container';
export { default as Grid } from '@mui/material/Grid';
export { default as Card } from '@mui/material/Card';
export { default as CardContent } from '@mui/material/CardContent';
export { default as CardActions } from '@mui/material/CardActions';
export { default as AppBar } from '@mui/material/AppBar';
export { default as Toolbar } from '@mui/material/Toolbar';
export { default as IconButton } from '@mui/material/IconButton';
export { default as Menu } from '@mui/material/Menu';
export { default as MenuItem } from '@mui/material/MenuItem';
export { default as List } from '@mui/material/List';
export { default as ListItem } from '@mui/material/ListItem';
export { default as ListItemText } from '@mui/material/ListItemText';
export { default as ListItemIcon } from '@mui/material/ListItemIcon';
export { default as Divider } from '@mui/material/Divider';
export { default as Dialog } from '@mui/material/Dialog';
export { default as DialogTitle } from '@mui/material/DialogTitle';
export { default as DialogContent } from '@mui/material/DialogContent';
export { default as DialogActions } from '@mui/material/DialogActions';
export { default as Table } from '@mui/material/Table';
export { default as TableBody } from '@mui/material/TableBody';
export { default as TableCell } from '@mui/material/TableCell';
export { default as TableContainer } from '@mui/material/TableContainer';
export { default as TableHead } from '@mui/material/TableHead';
export { default as TableRow } from '@mui/material/TableRow';
export { default as CircularProgress } from '@mui/material/CircularProgress';
export { default as LinearProgress } from '@mui/material/LinearProgress';
export { default as Alert } from '@mui/material/Alert';
export { default as Snackbar } from '@mui/material/Snackbar';
export { default as Chip } from '@mui/material/Chip';
export { default as Avatar } from '@mui/material/Avatar';
export { default as Badge } from '@mui/material/Badge';
export { default as Fab } from '@mui/material/Fab';
export { default as SpeedDial } from '@mui/material/SpeedDial';
export { default as SpeedDialAction } from '@mui/material/SpeedDialAction';
export { default as SpeedDialIcon } from '@mui/material/SpeedDialIcon';
export { default as Drawer } from '@mui/material/Drawer';
export { default as Tooltip } from '@mui/material/Tooltip';
export { default as Popover } from '@mui/material/Popover';
export { default as Accordion } from '@mui/material/Accordion';
export { default as AccordionSummary } from '@mui/material/AccordionSummary';
export { default as AccordionDetails } from '@mui/material/AccordionDetails';
export { default as Tabs } from '@mui/material/Tabs';
export { default as Tab } from '@mui/material/Tab';
export { default as Stepper } from '@mui/material/Stepper';
export { default as Step } from '@mui/material/Step';
export { default as StepLabel } from '@mui/material/StepLabel';
export { default as StepContent } from '@mui/material/StepContent';
export { default as FormControl } from '@mui/material/FormControl';
export { default as InputLabel } from '@mui/material/InputLabel';
export { default as Select } from '@mui/material/Select';
export { default as Checkbox } from '@mui/material/Checkbox';
export { default as FormControlLabel } from '@mui/material/FormControlLabel';
export { default as Radio } from '@mui/material/Radio';
export { default as RadioGroup } from '@mui/material/RadioGroup';
export { default as Switch } from '@mui/material/Switch';
export { default as Slider } from '@mui/material/Slider';
export { default as Rating } from '@mui/material/Rating';
export { default as Autocomplete } from '@mui/material/Autocomplete';
export { default as Pagination } from '@mui/material/Pagination';
export { default as Breadcrumbs } from '@mui/material/Breadcrumbs';
export { default as Link } from '@mui/material/Link';
export { default as Skeleton } from '@mui/material/Skeleton';
export { default as Backdrop } from '@mui/material/Backdrop';
export { default as Modal } from '@mui/material/Modal';
export { default as Fade } from '@mui/material/Fade';
export { default as Grow } from '@mui/material/Grow';
export { default as Slide } from '@mui/material/Slide';
export { default as Zoom } from '@mui/material/Zoom';
export { default as Collapse } from '@mui/material/Collapse';
export { default as ListItemButton } from '@mui/material/ListItemButton';
export { default as ListItemAvatar } from '@mui/material/ListItemAvatar';
export { default as ListSubheader } from '@mui/material/ListSubheader';
export { default as ListItemSecondaryAction } from '@mui/material/ListItemSecondaryAction';

// Iconos específicos (importar solo los que uses)
export { default as MenuIcon } from '@mui/icons-material/Menu';
export { default as SearchIcon } from '@mui/icons-material/Search';
export { default as AddIcon } from '@mui/icons-material/Add';
export { default as EditIcon } from '@mui/icons-material/Edit';
export { default as DeleteIcon } from '@mui/icons-material/Delete';
export { default as SaveIcon } from '@mui/icons-material/Save';
export { default as CancelIcon } from '@mui/icons-material/Cancel';
export { default as CloseIcon } from '@mui/icons-material/Close';
export { default as CheckIcon } from '@mui/icons-material/Check';
export { default as WarningIcon } from '@mui/icons-material/Warning';
export { default as ErrorIcon } from '@mui/icons-material/Error';
export { default as InfoIcon } from '@mui/icons-material/Info';
export { default as SuccessIcon } from '@mui/icons-material/CheckCircle';
export { default as HomeIcon } from '@mui/icons-material/Home';
export { default as DashboardIcon } from '@mui/icons-material/Dashboard';
export { default as PersonIcon } from '@mui/icons-material/Person';
export { default as SettingsIcon } from '@mui/icons-material/Settings';
export { default as LogoutIcon } from '@mui/icons-material/Logout';
export { default as LoginIcon } from '@mui/icons-material/Login';
export { default as VisibilityIcon } from '@mui/icons-material/Visibility';
export { default as VisibilityOffIcon } from '@mui/icons-material/VisibilityOff';
export { default as DownloadIcon } from '@mui/icons-material/Download';
export { default as UploadIcon } from '@mui/icons-material/Upload';
export { default as PrintIcon } from '@mui/icons-material/Print';
export { default as ShareIcon } from '@mui/icons-material/Share';
export { default as EmailIcon } from '@mui/icons-material/Email';
export { default as PhoneIcon } from '@mui/icons-material/Phone';
export { default as LocationOnIcon } from '@mui/icons-material/LocationOn';
export { default as CalendarTodayIcon } from '@mui/icons-material/CalendarToday';
export { default as AccessTimeIcon } from '@mui/icons-material/AccessTime';
export { default as NotificationsIcon } from '@mui/icons-material/Notifications';
export { default as AccountCircleIcon } from '@mui/icons-material/AccountCircle';
export { default as BusinessIcon } from '@mui/icons-material/Business';
export { default as StoreIcon } from '@mui/icons-material/Store';
export { default as AssessmentIcon } from '@mui/icons-material/Assessment';
export { default as BarChartIcon } from '@mui/icons-material/BarChart';
export { default as PieChartIcon } from '@mui/icons-material/PieChart';
export { default as TimelineIcon } from '@mui/icons-material/Timeline';
export { default as TrendingUpIcon } from '@mui/icons-material/TrendingUp';
export { default as TrendingDownIcon } from '@mui/icons-material/TrendingDown';
export { default as FilterListIcon } from '@mui/icons-material/FilterList';
export { default as SortIcon } from '@mui/icons-material/Sort';
export { default as RefreshIcon } from '@mui/icons-material/Refresh';
export { default as MoreVertIcon } from '@mui/icons-material/MoreVert';
export { default as MoreHorizIcon } from '@mui/icons-material/MoreHoriz';
export { default as ExpandMoreIcon } from '@mui/icons-material/ExpandMore';
export { default as ExpandLessIcon } from '@mui/icons-material/ExpandLess';
export { default as KeyboardArrowDownIcon } from '@mui/icons-material/KeyboardArrowDown';
export { default as KeyboardArrowUpIcon } from '@mui/icons-material/KeyboardArrowUp';
export { default as KeyboardArrowLeftIcon } from '@mui/icons-material/KeyboardArrowLeft';
export { default as KeyboardArrowRightIcon } from '@mui/icons-material/KeyboardArrowRight';
export { default as FirstPageIcon } from '@mui/icons-material/FirstPage';
export { default as LastPageIcon } from '@mui/icons-material/LastPage';
export { default as NavigateBeforeIcon } from '@mui/icons-material/NavigateBefore';
export { default as NavigateNextIcon } from '@mui/icons-material/NavigateNext';
export { default as FullscreenIcon } from '@mui/icons-material/Fullscreen';
export { default as FullscreenExitIcon } from '@mui/icons-material/FullscreenExit';
export { default as ZoomInIcon } from '@mui/icons-material/ZoomIn';
export { default as ZoomOutIcon } from '@mui/icons-material/ZoomOut';
export { default as ContentCopyIcon } from '@mui/icons-material/ContentCopy';
export { default as ContentCutIcon } from '@mui/icons-material/ContentCut';
export { default as ContentPasteIcon } from '@mui/icons-material/ContentPaste';
export { default as UndoIcon } from '@mui/icons-material/Undo';
export { default as RedoIcon } from '@mui/icons-material/Redo';
export { default as HelpIcon } from '@mui/icons-material/Help';
export { default as FeedbackIcon } from '@mui/icons-material/Feedback';
export { default as BugReportIcon } from '@mui/icons-material/BugReport';
export { default as CodeIcon } from '@mui/icons-material/Code';
export { default as BuildIcon } from '@mui/icons-material/Build';
export { default as SecurityIcon } from '@mui/icons-material/Security';
export { default as LockIcon } from '@mui/icons-material/Lock';
export { default as LockOpenIcon } from '@mui/icons-material/LockOpen';
export { default as VpnKeyIcon } from '@mui/icons-material/VpnKey';
export { default as KeyIcon } from '@mui/icons-material/Key';
export { default as FingerprintIcon } from '@mui/icons-material/Fingerprint';
export { default as VerifiedUserIcon } from '@mui/icons-material/VerifiedUser';
export { default as AdminPanelSettingsIcon } from '@mui/icons-material/AdminPanelSettings';
export { default as SupervisorAccountIcon } from '@mui/icons-material/SupervisorAccount';
export { default as GroupIcon } from '@mui/icons-material/Group';
export { default as GroupAddIcon } from '@mui/icons-material/GroupAdd';
export { default as PersonAddIcon } from '@mui/icons-material/PersonAdd';
export { default as PersonRemoveIcon } from '@mui/icons-material/PersonRemove';
export { default as BlockIcon } from '@mui/icons-material/Block';
export { default as ReportIcon } from '@mui/icons-material/Report';
export { default as FlagIcon } from '@mui/icons-material/Flag';
export { default as StarIcon } from '@mui/icons-material/Star';
export { default as StarBorderIcon } from '@mui/icons-material/StarBorder';
export { default as StarHalfIcon } from '@mui/icons-material/StarHalf';
export { default as FavoriteIcon } from '@mui/icons-material/Favorite';
export { default as FavoriteBorderIcon } from '@mui/icons-material/FavoriteBorder';
export { default as ThumbUpIcon } from '@mui/icons-material/ThumbUp';
export { default as ThumbDownIcon } from '@mui/icons-material/ThumbDown';
export { default as ThumbUpOutlinedIcon } from '@mui/icons-material/ThumbUpOutlined';
export { default as ThumbDownOutlinedIcon } from '@mui/icons-material/ThumbDownOutlined';
export { default as ReplyIcon } from '@mui/icons-material/Reply';
export { default as ReplyAllIcon } from '@mui/icons-material/ReplyAll';
export { default as ForwardIcon } from '@mui/icons-material/Forward';
export { default as SendIcon } from '@mui/icons-material/Send';
export { default as AttachFileIcon } from '@mui/icons-material/AttachFile';
export { default as InsertDriveFileIcon } from '@mui/icons-material/InsertDriveFile';
export { default as FolderIcon } from '@mui/icons-material/Folder';
export { default as FolderOpenIcon } from '@mui/icons-material/FolderOpen';
export { default as CreateNewFolderIcon } from '@mui/icons-material/CreateNewFolder';
export { default as CloudUploadIcon } from '@mui/icons-material/CloudUpload';
export { default as CloudDownloadIcon } from '@mui/icons-material/CloudDownload';
export { default as CloudIcon } from '@mui/icons-material/Cloud';
export { default as WifiIcon } from '@mui/icons-material/Wifi';
export { default as SignalWifi4BarIcon } from '@mui/icons-material/SignalWifi4Bar';
export { default as SignalCellular4BarIcon } from '@mui/icons-material/SignalCellular4Bar';
export { default as BatteryFullIcon } from '@mui/icons-material/BatteryFull';
export { default as BatteryChargingFullIcon } from '@mui/icons-material/BatteryChargingFull';
export { default as BatteryAlertIcon } from '@mui/icons-material/BatteryAlert';
export { default as BatteryUnknownIcon } from '@mui/icons-material/BatteryUnknown';
export { default as Brightness4Icon } from '@mui/icons-material/Brightness4';
export { default as Brightness7Icon } from '@mui/icons-material/Brightness7';
export { default as BrightnessAutoIcon } from '@mui/icons-material/BrightnessAuto';
export { default as PaletteIcon } from '@mui/icons-material/Palette';
export { default as ColorLensIcon } from '@mui/icons-material/ColorLens';
export { default as FormatColorFillIcon } from '@mui/icons-material/FormatColorFill';
export { default as FormatColorTextIcon } from '@mui/icons-material/FormatColorText';
export { default as FormatColorResetIcon } from '@mui/icons-material/FormatColorReset';
export { default as FormatBoldIcon } from '@mui/icons-material/FormatBold';
export { default as FormatItalicIcon } from '@mui/icons-material/FormatItalic';
export { default as FormatUnderlinedIcon } from '@mui/icons-material/FormatUnderlined';
export { default as FormatStrikethroughIcon } from '@mui/icons-material/FormatStrikethrough';
export { default as FormatAlignLeftIcon } from '@mui/icons-material/FormatAlignLeft';
export { default as FormatAlignCenterIcon } from '@mui/icons-material/FormatAlignCenter';
export { default as FormatAlignRightIcon } from '@mui/icons-material/FormatAlignRight';
export { default as FormatAlignJustifyIcon } from '@mui/icons-material/FormatAlignJustify';
export { default as FormatListBulletedIcon } from '@mui/icons-material/FormatListBulleted';
export { default as FormatListNumberedIcon } from '@mui/icons-material/FormatListNumbered';
export { default as FormatIndentIncreaseIcon } from '@mui/icons-material/FormatIndentIncrease';
export { default as FormatIndentDecreaseIcon } from '@mui/icons-material/FormatIndentDecrease';
export { default as FormatLineSpacingIcon } from '@mui/icons-material/FormatLineSpacing';
export { default as FormatSizeIcon } from '@mui/icons-material/FormatSize';
export { default as FormatClearIcon } from '@mui/icons-material/FormatClear';
export { default as InsertLinkIcon } from '@mui/icons-material/InsertLink';
export { default as InsertPhotoIcon } from '@mui/icons-material/InsertPhoto';
export { default as InsertVideoIcon } from '@mui/icons-material/InsertVideo';
export { default as InsertEmoticonIcon } from '@mui/icons-material/InsertEmoticon';
export { default as InsertChartIcon } from '@mui/icons-material/InsertChart';
export { default as InsertTableChartIcon } from '@mui/icons-material/InsertTableChart';
export { default as InsertDriveFileIcon as InsertFileIcon } from '@mui/icons-material/InsertDriveFile';
export { default as InsertInvitationIcon } from '@mui/icons-material/InsertInvitation';
export { default as InsertCommentIcon } from '@mui/icons-material/InsertComment';
export { default as FunctionsIcon } from '@mui/icons-material/Functions';
export { default as SubscriptIcon } from '@mui/icons-material/Subscript';
export { default as SuperscriptIcon } from '@mui/icons-material/Superscript';
export { default as SpaceBarIcon } from '@mui/icons-material/SpaceBar';
export { default as BorderColorIcon } from '@mui/icons-material/BorderColor';
export { default as FormatPaintIcon } from '@mui/icons-material/FormatPaint';
export { default as ModeEditIcon } from '@mui/icons-material/ModeEdit';
export { default as CreateIcon } from '@mui/icons-material/Create';
export { default as BrushIcon } from '@mui/icons-material/Brush';
export { default as HighlightIcon } from '@mui/icons-material/Highlight';
export { default as AutoFixHighIcon } from '@mui/icons-material/AutoFixHigh';
export { default as AutoFixNormalIcon } from '@mui/icons-material/AutoFixNormal';
export { default as AutoFixOffIcon } from '@mui/icons-material/AutoFixOff';
export { default as ContentPasteGoIcon } from '@mui/icons-material/ContentPasteGo';
export { default as ContentPasteSearchIcon } from '@mui/icons-material/ContentPasteSearch';
export { default as ContentPasteOffIcon } from '@mui/icons-material/ContentPasteOff';
export { default as ContentCutIcon as ContentCutOutlinedIcon } from '@mui/icons-material/ContentCutOutlined';
export { default as ContentCopyIcon as ContentCopyOutlinedIcon } from '@mui/icons-material/ContentCopyOutlined';
export { default as ContentPasteIcon as ContentPasteOutlinedIcon } from '@mui/icons-material/ContentPasteOutlined';
export { default as ContentPasteGoIcon as ContentPasteGoOutlinedIcon } from '@mui/icons-material/ContentPasteGoOutlined';
export { default as ContentPasteSearchIcon as ContentPasteSearchOutlinedIcon } from '@mui/icons-material/ContentPasteSearchOutlined';
export { default as ContentPasteOffIcon as ContentPasteOffOutlinedIcon } from '@mui/icons-material/ContentPasteOffOutlined';
export { default as ContentCutIcon as ContentCutRoundedIcon } from '@mui/icons-material/ContentCutRounded';
export { default as ContentCopyIcon as ContentCopyRoundedIcon } from '@mui/icons-material/ContentCopyRounded';
export { default as ContentPasteIcon as ContentPasteRoundedIcon } from '@mui/icons-material/ContentPasteRounded';
export { default as ContentPasteGoIcon as ContentPasteGoRoundedIcon } from '@mui/icons-material/ContentPasteGoRounded';
export { default as ContentPasteSearchIcon as ContentPasteSearchRoundedIcon } from '@mui/icons-material/ContentPasteSearchRounded';
export { default as ContentPasteOffIcon as ContentPasteOffRoundedIcon } from '@mui/icons-material/ContentPasteOffRounded';
export { default as ContentCutIcon as ContentCutSharpIcon } from '@mui/icons-material/ContentCutSharp';
export { default as ContentCopyIcon as ContentCopySharpIcon } from '@mui/icons-material/ContentCopySharp';
export { default as ContentPasteIcon as ContentPasteSharpIcon } from '@mui/icons-material/ContentPasteSharp';
export { default as ContentPasteGoIcon as ContentPasteGoSharpIcon } from '@mui/icons-material/ContentPasteGoSharp';
export { default as ContentPasteSearchIcon as ContentPasteSearchSharpIcon } from '@mui/icons-material/ContentPasteSearchSharp';
export { default as ContentPasteOffIcon as ContentPasteOffSharpIcon } from '@mui/icons-material/ContentPasteOffSharp';
export { default as ContentCutIcon as ContentCutTwoToneIcon } from '@mui/icons-material/ContentCutTwoTone';
export { default as ContentCopyIcon as ContentCopyTwoToneIcon } from '@mui/icons-material/ContentCopyTwoTone';
export { default as ContentPasteIcon as ContentPasteTwoToneIcon } from '@mui/icons-material/ContentPasteTwoTone';
export { default as ContentPasteGoIcon as ContentPasteGoTwoToneIcon } from '@mui/icons-material/ContentPasteGoTwoTone';
export { default as ContentPasteSearchIcon as ContentPasteSearchTwoToneIcon } from '@mui/icons-material/ContentPasteSearchTwoTone';
export { default as ContentPasteOffIcon as ContentPasteOffTwoToneIcon } from '@mui/icons-material/ContentPasteOffTwoTone';
